### ISSUE TITLE
Watch closing keynote of ElixirConf

### ISSUE THREAD

**Issue by clekstro** [clekstro/fridays#5]
http://confreaks.tv/videos/elixirconf2016-closing-keynote

**Comment by clekstro** [comment]
Done!

**Comment by taylorbrooks** [comment]
What'd you think?

**Comment by clekstro** [comment]
@taylorbrooks I quite liked it. 

First takeaway: I think the combo of OTP for supervision and then for really performance-sensitive stuff delegating off to something lower level makes a ton of sense. I think we had even discussed it the first night at the conference. Also, I'd never heard of FPGA's before, which sound AWESOME.

Second takeaway: I need to play with Nerves.

More generally, I liked his "right tool for the job" approach to technology and that he wasn't afraid to critique things in the ecosystem that he felt were currently underwhelming.
